clean:
	rm -rf ccfx libpicosellib.so picosel
	rm -rf scripts/easytorq.so
	rm -rf scripts/moduleloadutility.pyc
	rm -rf scripts/threadingutil.pyc
	rm -rf ubuntu32/scripts/pp/*.pyc
	rm -rf lib_CCFinderXLib.so
	rm -rf scripts/utility.pyc


all:
	echo 'Done'
